UnconnectedException: thrown when no sessioninfo is available (call connect first) AbstractMyJDClient: -refactored to store all info in SessionInfo, avoids inconsistent variable state (eg sessionToken set but encryptiontoken is null because of an error)